### ISSUE TITLE
検索結果のソートオーダーを指定したい

### ISSUE THREAD

**Issue by nalabjp** [nalabjp/ese#1]
っていう要望をチラッと聞いた。
コレ👇を検索時に指定したいらしい。
![2017-07-12 17 20 26](https://user-images.githubusercontent.com/1544172/28108416-5b26fa26-6726-11e7-8e71-abe89f9da851.png)

なるほど、理解はできる。
自分はほぼ使ってないけど。
他にも欲しい人がいたら考えようかな。🤔

**Comment by nhosoya** [comment]
したい :raising_hand_man: 🙋

**Comment by nalabjp** [comment]
> したい :raising_hand_man: 🙋

PRくれてもいいんですよ？ |дﾟ)ﾁﾗｯ

**Comment by nalabjp** [comment]
v1.2.0でサポートしました😌
