### ISSUE TITLE
キーワードに特定の文字列が入るとjsエラーになる

### ISSUE THREAD

**Issue by yori-a2c** [nalabjp/ese#6]
キーワードで特定の文字列（URLなどを）検索すると、valを取得する部分のjsでエラーとなり、後続の処理が止まります。
結果、後続処理の検索ボタンの作成が行われず、検索が出来ない状態となります。

キャプチャー
![image](https://user-images.githubusercontent.com/13588192/29664617-5de5f620-890b-11e7-95b8-515b50693e16.png)

**Comment by nalabjp** [comment]
@yori-a2c 
バグレポートありがとうございます！
遅くなってごめんなさい🙏
v1.2.0で修正したのでREADMEのリンクのstableから更新してください😌

**Comment by yori-a2c** [comment]
@nalabjp 
バグ修正確認できました！ありがとうございます 🙇 👍
